### PR TITLE
Angel tutorial 1

### PR DESCRIPTION
**Pull request by miguelglezb**
Adding intro tutorial from @angelrls training session.

### CODE REVIEW

**Comment by PabloCorcho** [comment]
Thanks Miguel, I will have a detailed look today. I see that there are some methods that perform unexpected operations with respect to the module where they are (e.g. statistics in a plotting module). We need to check this before merging.

**Comment by paranoya** [comment]
I just had a look, and I see a lot of duplicated effort. There are minor differences, though, and I'm sure the user interface will improve once we integrate everything into a consistent framework. The only change that I would strongly enforce is to remove the "Processing RSS files - DO NOT RUN FROM HERE !!!" part of the tutorial. Other than that, I do agree that we should definitely number the tutorials and/or provide well defined sequence(s) in the README file. Reading an RSS (from KOALA, or any other instrument) and plotting some maps and spectra are certainly reasonable first steps. I'm looking forward to seeing the other tutorials! Thinking out loud, we might even divide them into "basic" and "advanced". I guess many users would be happy to use our code just to read intensities and variances for further analysis, whereas others would be interested in the gory details of sky subtraction, wavelength calibration, fibre throughput, and such.

**Comment by miguelglezb** [comment]
I agree with both of you. Two things though:
- I believe that @angelrls wants to show the parameter list of `process_koala_rss` for the last two cells, that is why I changed them from python lines into markdown.  
- Although I love the idea of dividing the tutorials into "basic" and "advanced", I wonder if that can be done (decided) in the time we have for the training. For long term I say definitely yes!

**Comment by PabloCorcho** [comment]
For the sake of the workshop, let's merge this branch. Afterwards, we will do the refactoring. That will be a good moment for implementing the changes of #439. Unfortunately, this will probably break backwards compatibility with the methods that will be shown in the tutorials (but hopefully the supadupa pykoala documentation will make things easier in the future).

**Review by PabloCorcho — APPROVED** [review]

**Comment by PabloCorcho** [comment]
@miguelglezb I changed you role in the project. Now you can create your own branches/PR within pykoala without the need for forking. This way it is much easier for us to check the changes locally.

**Pull request merged**
